"""SQLAlchemy Core tables for schema ``platform`` (DDL lives in migration 0005_platform).

Only the columns the service uses are declared; the database enforces the rest (CHECKs,
triggers). Everything here is reached through ``core.db.platform_session()`` (sos_platform).
"""

from __future__ import annotations

from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    Date,
    DateTime,
    Integer,
    LargeBinary,
    MetaData,
    Numeric,
    SmallInteger,
    Table,
    Text,
    Uuid,
)
from sqlalchemy.dialects.postgresql import ARRAY, CITEXT, JSONB

metadata = MetaData(schema="platform")

operators = Table(
    "operators",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("idp_subject", Text),
    Column("email", CITEXT, nullable=False),
    Column("display_name", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("mfa_enrolled", Boolean, nullable=False),
    Column("invited_by", Uuid),
    Column("created_at", DateTime(timezone=True)),
    Column("last_login_at", DateTime(timezone=True)),
    Column("deactivated_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
    Column("version", Integer),
)

operator_roles = Table(
    "operator_roles",
    metadata,
    Column("operator_id", Uuid, primary_key=True),
    Column("role_key", Text, primary_key=True),
    Column("granted_by", Uuid),
    Column("granted_at", DateTime(timezone=True)),
)

plans = Table(
    "plans",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("code", Text, nullable=False),
    Column("version", Integer, nullable=False),
    Column("name", Text, nullable=False),
    Column("tier", Text, nullable=False),
    Column("billing_period", Text, nullable=False),
    Column("pricing_model", Text, nullable=False),
    Column("base_price_inr", Numeric(14, 2), nullable=False),
    Column("per_student_price_inr", Numeric(14, 2)),
    Column("included_students", Integer),
    Column("gst_rate", Numeric(5, 2), nullable=False),
    Column("sac_code", Text, nullable=False),
    Column("trial_days", Integer, nullable=False),
    Column("limits", JSONB, nullable=False),
    Column("features", JSONB, nullable=False),
    Column("status", Text, nullable=False),
    Column("published_at", DateTime(timezone=True)),
    Column("created_by", Uuid, nullable=False),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
)

billing_accounts = Table(
    "billing_accounts",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("tenant_id", Uuid, nullable=False),
    Column("legal_name", Text, nullable=False),
    Column("gstin", Text),
    Column("pan", Text),
    Column("billing_email", CITEXT, nullable=False),
    Column("billing_contact_name", Text),
    Column("billing_phone", Text),
    Column("address_line1", Text, nullable=False),
    Column("address_line2", Text),
    Column("city", Text, nullable=False),
    Column("district", Text),
    Column("postal_code", Text, nullable=False),
    Column("state_code", Text, nullable=False),
    Column("po_reference", Text),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
    Column("version", Integer),
)

deployments = Table(
    "deployments",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("tenant_id", Uuid, nullable=False),
    Column("tenant_code", Text, nullable=False),
    Column("school_name", Text, nullable=False),
    Column("boards", ARRAY(Text), nullable=False),
    Column("mode", Text, nullable=False),
    Column("region", Text),
    Column("backup_region", Text),
    Column("host_ref", Text),
    Column("hostname", Text),
    Column("custom_domain", CITEXT),
    Column("tenant_status", Text, nullable=False),
    Column("tenant_status_reason", Text),
    Column("status", Text, nullable=False),
    Column("app_version", Text),
    Column("target_version", Text),
    Column("last_heartbeat_at", DateTime(timezone=True)),
    Column("last_heartbeat", JSONB),
    Column("heartbeat_key_id", Text),
    Column("heartbeat_key_ciphertext", LargeBinary),
    Column("heartbeat_next_key_id", Text),
    Column("heartbeat_next_key_ciphertext", LargeBinary),
    Column("heartbeat_rotation_started_at", DateTime(timezone=True)),
    Column("offboard_requested_by", Uuid),
    Column("offboard_requested_at", DateTime(timezone=True)),
    Column("offboard_reason", Text),
    Column("offboard_approved_by", Uuid),
    Column("offboard_approved_at", DateTime(timezone=True)),
    Column("deletion_certificate_ref", Text),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
    Column("version", Integer),
)

subscriptions = Table(
    "subscriptions",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("tenant_id", Uuid, nullable=False),
    Column("billing_account_id", Uuid, nullable=False),
    Column("plan_id", Uuid, nullable=False),
    Column("pending_plan_id", Uuid),
    Column("status", Text, nullable=False),
    Column("trial_ends_at", DateTime(timezone=True)),
    Column("current_period_start", Date, nullable=False),
    Column("current_period_end", Date, nullable=False),
    Column("price_override_inr", Numeric(14, 2)),
    Column("override_reason", Text),
    Column("past_due_since", Date),
    Column("grace_ends_on", Date),
    Column("suspended_at", DateTime(timezone=True)),
    Column("suspended_by", Uuid),
    Column("suspension_reason", Text),
    Column("exam_window_override_by", Uuid),
    Column("cancel_at_period_end", Boolean, nullable=False),
    Column("cancelled_at", DateTime(timezone=True)),
    Column("cancel_reason", Text),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
    Column("version", Integer),
)

invoice_sequences = Table(
    "invoice_sequences",
    metadata,
    Column("financial_year", Text, primary_key=True),
    Column("prefix", Text),
    Column("last_number", Integer, nullable=False),
    Column("updated_at", DateTime(timezone=True)),
)

invoices = Table(
    "invoices",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("tenant_id", Uuid, nullable=False),
    Column("subscription_id", Uuid, nullable=False),
    Column("billing_account_id", Uuid, nullable=False),
    Column("status", Text, nullable=False),
    Column("financial_year", Text),
    Column("sequence_no", Integer),
    Column("invoice_number", Text),
    Column("period_start", Date, nullable=False),
    Column("period_end", Date, nullable=False),
    Column("issue_date", Date),
    Column("due_date", Date),
    Column("currency", Text),
    Column("supplier_legal_name", Text, nullable=False),
    Column("supplier_gstin", Text, nullable=False),
    Column("supplier_state_code", Text, nullable=False),
    Column("recipient_legal_name", Text, nullable=False),
    Column("recipient_gstin", Text),
    Column("recipient_address", JSONB, nullable=False),
    Column("place_of_supply_state_code", Text, nullable=False),
    Column("tax_type", Text, nullable=False),
    Column("taxable_value_inr", Numeric(14, 2), nullable=False),
    Column("cgst_inr", Numeric(14, 2), nullable=False),
    Column("sgst_inr", Numeric(14, 2), nullable=False),
    Column("igst_inr", Numeric(14, 2), nullable=False),
    Column("total_inr", Numeric(14, 2), nullable=False),
    Column("amount_paid_inr", Numeric(14, 2), nullable=False),
    Column("tds_inr", Numeric(14, 2), nullable=False),
    Column("notes", Text),
    Column("issued_by", Uuid),
    Column("issued_at", DateTime(timezone=True)),
    Column("voided_by", Uuid),
    Column("voided_at", DateTime(timezone=True)),
    Column("void_reason", Text),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
    Column("version", Integer),
)

invoice_lines = Table(
    "invoice_lines",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("invoice_id", Uuid, nullable=False),
    Column("line_no", Integer, nullable=False),
    Column("kind", Text, nullable=False),
    Column("description", Text, nullable=False),
    Column("sac_code", Text, nullable=False),
    Column("quantity", Numeric(12, 3), nullable=False),
    Column("unit_price_inr", Numeric(14, 2), nullable=False),
    Column("amount_inr", Numeric(14, 2), nullable=False),
    Column("gst_rate", Numeric(5, 2), nullable=False),
)

payments = Table(
    "payments",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("invoice_id", Uuid, nullable=False),
    Column("tenant_id", Uuid, nullable=False),
    Column("provider", Text, nullable=False),
    Column("method", Text, nullable=False),
    Column("amount_inr", Numeric(14, 2), nullable=False),
    Column("tds_inr", Numeric(14, 2), nullable=False),
    Column("received_on", Date, nullable=False),
    Column("reference", Text, nullable=False),
    Column("provider_payment_id", Text),
    Column("status", Text, nullable=False),
    Column("notes", Text),
    Column("recorded_by", Uuid, nullable=False),
    Column("recorded_at", DateTime(timezone=True)),
    Column("reversed_by", Uuid),
    Column("reversed_at", DateTime(timezone=True)),
    Column("reversal_reason", Text),
)

usage_daily = Table(
    "usage_daily",
    metadata,
    Column("tenant_id", Uuid, primary_key=True),
    Column("usage_date", Date, primary_key=True),
    Column("source", Text, nullable=False),
    Column("active_users", Integer, nullable=False),
    Column("staff_users", Integer, nullable=False),
    Column("students_active", Integer, nullable=False),
    Column("storage_bytes", BigInteger, nullable=False),
    Column("documents", Integer, nullable=False),
    Column("ai_queries", Integer, nullable=False),
    Column("ai_input_tokens", BigInteger, nullable=False),
    Column("ai_output_tokens", BigInteger, nullable=False),
    Column("ai_cost_usd", Numeric(14, 4), nullable=False),
    Column("ai_cost_inr", Numeric(14, 2), nullable=False),
    Column("collected_at", DateTime(timezone=True)),
)

usage_threshold_events = Table(
    "usage_threshold_events",
    metadata,
    Column("tenant_id", Uuid, primary_key=True),
    Column("metric", Text, primary_key=True),
    Column("threshold", SmallInteger, primary_key=True),
    Column("period_start", Date, primary_key=True),
    Column("usage_value", Numeric(20, 2), nullable=False),
    Column("limit_value", Numeric(20, 2), nullable=False),
    Column("crossed_at", DateTime(timezone=True)),
)

feature_flags = Table(
    "feature_flags",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("key", Text, nullable=False),
    Column("tenant_id", Uuid),
    Column("enabled", Boolean, nullable=False),
    Column("rollout_percent", SmallInteger),
    Column("description", Text),
    Column("updated_by", Uuid),
    Column("updated_at", DateTime(timezone=True)),
    Column("version", Integer),
)

announcements = Table(
    "announcements",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("title_en", Text, nullable=False),
    Column("title_te", Text, nullable=False),
    Column("body_en", Text, nullable=False),
    Column("body_te", Text, nullable=False),
    Column("severity", Text, nullable=False),
    Column("audience", Text, nullable=False),
    Column("audience_tier", Text),
    Column("audience_tenant_ids", ARRAY(Uuid), nullable=False),
    Column("starts_at", DateTime(timezone=True), nullable=False),
    Column("ends_at", DateTime(timezone=True), nullable=False),
    Column("status", Text, nullable=False),
    Column("created_by", Uuid, nullable=False),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
    Column("version", Integer),
)

support_tickets = Table(
    "support_tickets",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("ticket_no", BigInteger),
    Column("tenant_id", Uuid, nullable=False),
    Column("opened_by_user_id", Uuid),
    Column("opened_by_operator_id", Uuid),
    Column("channel", Text, nullable=False),
    Column("category", Text, nullable=False),
    Column("priority", Text, nullable=False),
    Column("subject", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("assigned_to", Uuid),
    Column("first_response_due_at", DateTime(timezone=True), nullable=False),
    Column("resolution_due_at", DateTime(timezone=True), nullable=False),
    Column("first_responded_at", DateTime(timezone=True)),
    Column("resolved_at", DateTime(timezone=True)),
    Column("closed_at", DateTime(timezone=True)),
    Column("personal_data_flagged", Boolean, nullable=False),
    Column("purge_after", Date),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
    Column("version", Integer),
)

support_messages = Table(
    "support_messages",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("ticket_id", Uuid, nullable=False),
    Column("author_type", Text, nullable=False),
    Column("author_id", Uuid),
    Column("body", Text, nullable=False),
    Column("internal_note", Boolean, nullable=False),
    Column("created_at", DateTime(timezone=True)),
)

breakglass_requests = Table(
    "breakglass_requests",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("tenant_id", Uuid, nullable=False),
    Column("requested_by", Uuid, nullable=False),
    Column("reason_code", Text, nullable=False),
    Column("reason", Text, nullable=False),
    Column("scope", JSONB, nullable=False),
    Column("duration_minutes", Integer, nullable=False),
    Column("emergency", Boolean, nullable=False),
    Column("status", Text, nullable=False),
    Column("emergency_confirmed_by_1", Uuid),
    Column("emergency_confirmed_by_2", Uuid),
    Column("emergency_confirmed_at", DateTime(timezone=True)),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
    Column("version", Integer),
)

job_runs = Table(
    "job_runs",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("task_name", Text, nullable=False),
    Column("idempotency_key", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("attempts", Integer, nullable=False),
    Column("progress", JSONB),
    Column("error", Text),
    Column("created_by", Uuid),
    Column("started_at", DateTime(timezone=True)),
    Column("finished_at", DateTime(timezone=True)),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
)

audit_events = Table(
    "audit_events",
    metadata,
    Column("id", Uuid, primary_key=True),
    Column("seq", BigInteger, nullable=False),
    Column("occurred_at", DateTime(timezone=True), nullable=False),
    Column("actor_type", Text, nullable=False),
    Column("actor_id", Uuid),
    Column("action", Text, nullable=False),
    Column("resource_type", Text, nullable=False),
    Column("resource_id", Uuid),
    Column("subject_tenant_id", Uuid),
    Column("summary", JSONB, nullable=False),
    Column("request_id", Text),
)
