"""Safe cells and tabular writers for exports (SEC-017, invariant 4; FR-EXP-002, FR-EXP-003).

Pure module (no database or web). Every value that goes into an exported file passes through
:func:`safe_cell`:

1. ``None`` becomes an empty cell; text is NFC-normalised and control characters other than
   tab, line feed and carriage return are removed (they are invalid in XLSX and useless in CSV).
2. :func:`app.core.redaction.mask_aadhaar` masks any 12-digit sequence that passes the Verhoeff
   check (invariant 4: no Aadhaar numbers, ever, in any exported cell). The one exception is a
   :class:`TypedDigits12` cell: the value of the typed ``apaar_id`` attribute (exactly 12 ASCII
   digits from a field whose type and source are known; ADR-0037 option (a), PRV-020). Only the
   exports service creates one, for that column; free text never does.
3. Formula injection (SEC-017, docs/07 §10): a cell that starts with ``=``, ``+``, ``-``, ``@``,
   tab or carriage return is prefixed with an apostrophe, so spreadsheet programs show it as
   text and never evaluate it.

XLSX cells are additionally written as explicit strings (type ``s``, text number format), so a
value is never stored as a formula even if a future change skipped step 3. Every file carries
the bilingual watermark "Generated by SchoolOS for internal checking" (US-901 AC2).
"""

from __future__ import annotations

import csv
import io
import re
import unicodedata
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from typing import Final

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from app.core.redaction import mask_aadhaar

FORMULA_TRIGGERS: Final = ("=", "+", "-", "@", "\t", "\r")
NEUTRALISER: Final = "'"
_CONTROL_RE: Final = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")
_SHEET_NAME_BAD: Final = re.compile(r"[\[\]:*?/\\]")
MAX_CELL_CHARS: Final = 32_000  # XLSX limit is 32,767 characters per cell
CSV_BOM: Final = "﻿"  # Excel opens UTF-8 (Telugu) correctly only with a BOM
XLSX_MIME: Final = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
CSV_MIME: Final = "text/csv"
PDF_MIME: Final = "application/pdf"


_DIGITS12_RE: Final = re.compile(r"[0-9]{12}")


class TypedDigits12(str):
    """The typed APAAR ID of one student (ADR-0037): exactly 12 ASCII digits, exported as is."""

    __slots__ = ()

    def __new__(cls, value: str) -> TypedDigits12:
        if _DIGITS12_RE.fullmatch(value) is None:
            raise ValueError("a typed digits12 cell holds exactly 12 ASCII digits")
        return super().__new__(cls, value)


def typed_digits12(value: str) -> str:
    """``value`` as a :class:`TypedDigits12` cell when it is exactly 12 ASCII digits; otherwise
    unchanged (and masked like any other text)."""
    return TypedDigits12(value) if _DIGITS12_RE.fullmatch(value) else value


def neutralise_formula(text: str) -> str:
    """Prefix ``'`` when ``text`` would start a formula (SEC-017)."""
    return NEUTRALISER + text if text.startswith(FORMULA_TRIGGERS) else text


def clean_text(value: object) -> str:
    """Steps 1 and 2: NFC, no control characters, Aadhaar-like numbers masked (invariant 4).
    Used as is for PDF text (nothing evaluates formulas there)."""
    if value is None:
        return ""
    if isinstance(value, TypedDigits12) and _DIGITS12_RE.fullmatch(value):
        return str(value)  # ADR-0037: the typed APAAR ID column, never free text
    text = unicodedata.normalize("NFC", str(value))
    text = _CONTROL_RE.sub("", text)
    text = mask_aadhaar(text)
    return text[:MAX_CELL_CHARS]


def safe_cell(value: object) -> str:
    """The text written to a spreadsheet or CSV cell: :func:`clean_text` plus formula
    neutralisation (SEC-017)."""
    return neutralise_formula(clean_text(value))


@dataclass(frozen=True, slots=True)
class Table:
    """One sheet (XLSX) or one file (CSV): a header row and data rows of plain values."""

    name: str
    header: tuple[str, ...]
    rows: tuple[tuple[object, ...], ...]

    def __post_init__(self) -> None:
        width = len(self.header)
        if any(len(r) != width for r in self.rows):
            raise ValueError("every row must have one value per header column")


def sheet_title(name: str, used: set[str]) -> str:
    """A valid, unique worksheet title (at most 31 characters, no ``[]:*?/\\``)."""
    base = _SHEET_NAME_BAD.sub(" ", unicodedata.normalize("NFC", name)).strip()[:31] or "Sheet"
    title, n = base, 2
    while title.lower() in used:
        suffix = f" ({n})"
        title, n = base[: 31 - len(suffix)] + suffix, n + 1
    used.add(title.lower())
    return title


def write_csv(table: Table, *, watermark: str) -> bytes:
    """UTF-8 CSV (with BOM): the watermark line, the header, then the rows."""
    out = io.StringIO()
    out.write(CSV_BOM)
    writer = csv.writer(out, lineterminator="\r\n", quoting=csv.QUOTE_MINIMAL)
    writer.writerow([safe_cell(watermark)])
    writer.writerow([safe_cell(h) for h in table.header])
    for row in table.rows:
        writer.writerow([safe_cell(v) for v in row])
    return out.getvalue().encode("utf-8")


_HEADER_FONT: Final = Font(bold=True)
_HEADER_FILL: Final = PatternFill("solid", fgColor="F1F1F1")
_WRAP: Final = Alignment(wrap_text=True, vertical="top")


def _put(ws: object, row: int, col: int, value: object) -> None:
    cell = ws.cell(row=row, column=col)  # type: ignore[attr-defined]
    cell.value = safe_cell(value)
    cell.data_type = "s"  # never a formula, whatever the text
    cell.number_format = "@"
    cell.alignment = _WRAP


def _widths(table: Table) -> list[int]:
    widths = [len(h) for h in table.header]
    for row in table.rows[:500]:
        for i, v in enumerate(row):
            widths[i] = max(widths[i], len(str(v or "")))
    return [min(max(w + 2, 8), 60) for w in widths]


def write_xlsx(tables: Sequence[Table], *, watermark: str, title: str) -> bytes:
    """One worksheet per table: bold frozen header, text cells, A4 landscape print setup and
    the watermark in every printed page header."""
    wb = Workbook()
    wb.remove(wb.active)  # type: ignore[arg-type]
    wb.properties.creator = "SchoolOS"
    wb.properties.title = safe_cell(title)
    wb.properties.description = safe_cell(watermark)
    used: set[str] = set()
    for table in tables:
        ws = wb.create_sheet(sheet_title(table.name, used))
        for col, text in enumerate(table.header, start=1):
            _put(ws, 1, col, text)
            ws.cell(row=1, column=col).font = _HEADER_FONT
            ws.cell(row=1, column=col).fill = _HEADER_FILL
        for r, row in enumerate(table.rows, start=2):
            for col, value in enumerate(row, start=1):
                _put(ws, r, col, value)
        for i, width in enumerate(_widths(table), start=1):
            ws.column_dimensions[get_column_letter(i)].width = width
        ws.freeze_panes = "A2"
        ws.page_setup.paperSize = ws.PAPERSIZE_A4
        ws.page_setup.orientation = ws.ORIENTATION_LANDSCAPE
        ws.page_setup.fitToWidth = 1
        ws.page_setup.fitToHeight = 0
        ws.sheet_properties.pageSetUpPr.fitToPage = True
        ws.print_title_rows = "1:1"
        ws.oddHeader.center.text = safe_cell(watermark).replace("&", "&&")
        ws.oddFooter.right.text = "&P / &N"
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def rows_of(values: Iterable[Sequence[object]]) -> tuple[tuple[object, ...], ...]:
    return tuple(tuple(v) for v in values)


__all__ = [
    "CSV_MIME",
    "FORMULA_TRIGGERS",
    "PDF_MIME",
    "XLSX_MIME",
    "Table",
    "TypedDigits12",
    "clean_text",
    "neutralise_formula",
    "rows_of",
    "safe_cell",
    "sheet_title",
    "typed_digits12",
    "write_csv",
    "write_xlsx",
]
