"""Export service end to end with the real database, DQ engine and student service (US-501 AC4,
US-901; FR-EXP-001..004; SEC-015, SEC-017; invariants 3, 4, 7). Synthetic data only."""

from __future__ import annotations

import csv
import dataclasses
import datetime as dt
import io
import sys
import uuid
from typing import Any

import pytest
from openpyxl import load_workbook
from sqlalchemy import Engine, text

from app.authz.context import Scopes
from app.core.db import tenant_session
from app.core.errors import Conflict, Forbidden, NotFound, StepUpRequired, ValidationFailed
from app.core.redaction import contains_full_aadhaar
from app.exports import service as exports
from app.students.schemas import ValueIn

pytestmark = pytest.mark.db
EX = sys.modules["sos_test_exports_objects"]
AAD = "aadhaar_as_printed"


def _xlsx(export_id: uuid.UUID) -> Any:
    return load_workbook(io.BytesIO(EX.stored(export_id, "xlsx")))


def _sheet(wb: Any, index: int) -> list[list[Any]]:
    return [[c.value for c in row] for row in wb.worksheets[index].iter_rows()]


@pytest.fixture
def section(school: Any, admin_engine: Engine) -> str:
    """A fresh section of the current year for one test (so its students are known)."""
    from app.tenancy import service as tenancy
    from app.tenancy.schemas import SectionCreate

    with tenant_session(school.tenant_id, school.people["owner"].user_id) as db:
        sec = tenancy.create_section(
            db,
            SectionCreate(
                academic_year_id=school.ids["year"],
                class_id=school.ids["class_ix"],
                name=f"T{uuid.uuid4().hex[:6].upper()}",
            ),
        )
    key = f"section_{sec.id}"
    school.ids[key] = sec.id
    return key


# --- pre-check -----------------------------------------------------------------------------------


def test_US_501_AC4_precheck_xlsx_and_pdf(school: Any, section: str, admin_engine: Engine) -> None:
    ready = EX.student(school, section_key=section, roll_no="2", name="Synthetica Ready Two")
    blocked = EX.student(school, section_key=section, roll_no="1", parents=False)
    warned = EX.student(
        school,
        section_key=section,
        roll_no="3",
        extra=[ValueIn(attribute_key="aadhaar_gender_as_printed", source=AAD, value="male")],
    )
    coordinator = school.people["exam_coordinator"]
    out = EX.request_precheck(school, coordinator, "exam_coordinator", section_keys=(section,))
    assert out.status == "queued"
    assert out.kind == "board_precheck"
    assert out.student_count == 3
    row = EX.export_row(admin_engine, out.id)
    assert sorted(row["student_ids"]) == sorted([ready, blocked, warned])
    assert EX.run(school, out.id) == "ready"

    row = EX.export_row(admin_engine, out.id)
    assert row["status"] == "ready"
    assert row["expires_at"] - row["finished_at"] == dt.timedelta(days=7)
    files = EX.files(admin_engine, out.id)
    assert [f["format"] for f in files] == ["pdf", "xlsx"]
    for f in files:
        assert f["object_key"].startswith(f"t/{school.tenant_id}/exports/{out.id}/")
    assert EX.stored(out.id, "pdf") == EX.PDF_BYTES

    wb = _xlsx(out.id)
    assert [ws.title for ws in wb.worksheets] == ["Summary", "Findings", "Ready to enter"]
    findings = _sheet(wb, 1)
    assert findings[0][0] == "Severity"
    severities = [r[0] for r in findings[1:]]
    assert severities[0] == "Blocker", "blockers first (US-501 AC2)"
    assert severities == sorted(
        severities, key=["Blocker", "High", "Medium", "Low", "Information"].index
    )
    rules = {r[4] for r in findings[1:]}
    assert {"DQ-005", "DQ-003"} <= rules
    ready_sheet = _sheet(wb, 2)
    assert ready_sheet[0] == [
        "Admission number",
        "Full name",
        "Gender",
        "Date of birth",
        "Father's name",
        "Mother's name",
        "Pre-check status",
    ]
    by_name = {r[1]: r for r in ready_sheet[1:]}
    assert by_name["Synthetica Ready Two"][2:4] == ["F", "14/03/2012"]
    statuses = [r[-1] for r in ready_sheet[1:]]
    # Unverified register values are low-severity warnings (DQ-005), so nobody is "Ready" yet.
    assert statuses == ["Blocked - fix first", "Check warnings", "Check warnings"], "by roll no"
    # The PDF was rendered from the escaped print page with the same findings.
    page = EX.FAKE.pages[-1]
    assert "Generated by SchoolOS for internal checking" in page
    assert "DQ-005" in page


def test_FR_EXP_003_precheck_audited_with_ids_and_counts(
    school: Any, section: str, admin_engine: Engine
) -> None:
    sid = EX.student(school, section_key=section)
    principal = school.people["principal"]
    out = EX.request_precheck(school, principal, "principal", section_keys=(section,))
    EX.run(school, out.id)
    rows = EX.audit_rows(admin_engine, school.tenant_id, out.id)
    actions = [r["action"] for r in rows]
    assert actions == ["export.requested", "export.completed"]
    requested = rows[0]["summary"]
    assert requested["kind"] == "board_precheck"
    assert requested["profile_key"] == "cisce-registration-2026"
    assert requested["profile_version"] == 1
    assert requested["students"] == 1
    assert requested["student_ids_digest"] == exports.student_ids_digest([sid])
    assert rows[0]["actor_id"] == principal.user_id
    completed = rows[1]["summary"]
    assert completed["students"] == 1
    assert {f["format"] for f in completed["files"]} == {"xlsx", "pdf"}
    # Notifications and the job run.
    assert EX.notifications(admin_engine, school.tenant_id, out.id) == [
        ("export.ready", principal.membership_id)
    ]
    with admin_engine.connect() as c:
        job = c.execute(
            text("SELECT task_name, status FROM ops.job_runs WHERE id = :j"),
            {"j": EX.export_row(admin_engine, out.id)["job_id"]},
        ).one()
    assert tuple(job) == ("exports.render", "succeeded")


def test_docs_04_queue_by_format(school: Any, section: str, admin_engine: Engine) -> None:
    EX.student(school, section_key=section)
    xlsx_only = EX.request_precheck(
        school, school.people["principal"], "principal", section_keys=(section,), formats=("xlsx",)
    )
    with_pdf = EX.request_precheck(
        school, school.people["principal"], "principal", section_keys=(section,), formats=("pdf",)
    )
    with admin_engine.connect() as c:
        events: dict[str, str] = dict(
            c.execute(
                text(
                    "SELECT payload ->> 'export_id', event_type FROM ops.outbox "
                    "WHERE tenant_id = :t AND event_type LIKE 'export.%'"
                ),
                {"t": school.tenant_id},
            ).all()
        )
    assert events[str(xlsx_only.id)] == "export.requested"
    assert events[str(with_pdf.id)] == "export.render_requested"


def test_FR_EXP_002_telugu_precheck(school: Any, section: str) -> None:
    EX.student(school, section_key=section, parents=False)
    out = EX.request_precheck(
        school,
        school.people["office_admin"],
        "office_admin",
        section_keys=(section,),
        formats=("xlsx",),
        language="te",
    )
    EX.run(school, out.id)
    wb = _xlsx(out.id)
    assert [ws.title for ws in wb.worksheets] == ["సారాంశం", "సమస్యలు", "నమోదుకు సిద్ధం"]
    findings = _sheet(wb, 1)
    assert findings[1][0] == "సమర్పణను ఆపేది"
    assert any("ఀ" <= ch <= "౿" for ch in str(findings[1][7]))


def test_portal_precheck_masks_c3_unless_included(
    school: Any, section: str, admin_engine: Engine
) -> None:
    EX.student(
        school,
        section_key=section,
        extra=[
            ValueIn(attribute_key="category", source="parent_form", value="obc"),
            ValueIn(attribute_key="mother_tongue", source="parent_form", value="Telugu"),
            ValueIn(attribute_key="aadhaar_last4", source=AAD, value="4821"),
            ValueIn(attribute_key="aadhaar_name_as_printed", source=AAD, value="Synthetica Aad"),
        ],
    )
    admin = school.people["office_admin"]
    masked = EX.request_precheck(
        school, admin, "office_admin", profile_key="udise-plus", section_keys=(section,)
    )
    assert masked.kind == "portal_precheck"
    EX.run(school, masked.id)
    ready = _sheet(_xlsx(masked.id), 2)
    header = ready[0]
    assert header[header.index("Social category")] == "Social category"
    assert ready[1][header.index("Social category")] == "••••"
    assert ready[1][header.index("Mother tongue")] == "Telugu"
    summary = _sheet(_xlsx(masked.id), 0)
    assert any("Restricted values are hidden" in str(r[1]) for r in summary)

    shown = EX.request_precheck(
        school,
        admin,
        "office_admin",
        profile_key="udise-plus",
        section_keys=(section,),
        include_sensitive=True,
    )
    EX.run(school, shown.id)
    ready = _sheet(_xlsx(shown.id), 2)
    assert ready[1][ready[0].index("Social category")] == "OBC"
    requested = EX.audit_rows(admin_engine, school.tenant_id, shown.id)[0]["summary"]
    assert requested["include_sensitive"] is True
    # ADR-0021 decision 2: the audit event names the restricted columns, never their values.
    assert requested["sensitive_columns"] == ["category"]
    assert "obc" not in str(requested).lower()
    unmasked = EX.audit_rows(admin_engine, school.tenant_id, masked.id)[0]["summary"]
    assert (unmasked["include_sensitive"], unmasked["sensitive_columns"]) == (False, [])
    # Aadhaar-as-printed values never appear in any file (PRV-013).
    for export_id in (masked.id, shown.id):
        for ws in _xlsx(export_id).worksheets:
            for row in ws.iter_rows():
                for cell in row:
                    assert "Synthetica Aad" not in str(cell.value or "")
    assert "Synthetica Aad" not in "".join(EX.FAKE.pages)


def test_include_sensitive_needs_permission_and_step_up(school: Any, section: str) -> None:
    EX.student(school, section_key=section)
    coordinator = school.people["exam_coordinator"]
    with pytest.raises(Forbidden) as exc:
        EX.request_precheck(
            school, coordinator, "exam_coordinator", section_keys=(section,), include_sensitive=True
        )
    assert exc.value.code == "sensitive_not_allowed"
    admin = school.people["office_admin"]
    stale = dataclasses.replace(EX.ctx(school, admin, "office_admin"), auth_time=None)
    with pytest.raises(StepUpRequired):
        EX.request_precheck(
            school,
            admin,
            "office_admin",
            section_keys=(section,),
            include_sensitive=True,
            as_ctx=stale,
        )


@pytest.mark.parametrize(
    "auth",
    [
        {"auth_time": None},
        {"auth_time": dt.datetime.now(dt.UTC) - dt.timedelta(minutes=6)},
        {"mfa": False},
    ],
    ids=["no-sign-in-time", "stale", "no-mfa"],
)
def test_ADR_0021_every_export_request_needs_step_up(
    school: Any, section: str, auth: dict[str, Any]
) -> None:
    """Decision 1: every pre-check (with or without restricted values) and every student list
    needs MFA within 5 minutes; the service checks it too, not only the route guard."""
    EX.student(school, section_key=section)
    who = school.people["exam_coordinator"]
    stale = dataclasses.replace(EX.ctx(school, who, "exam_coordinator"), **auth)
    for profile in ("cisce-registration-2026", "udise-plus"):
        with pytest.raises(StepUpRequired):
            EX.request_precheck(
                school,
                who,
                "exam_coordinator",
                profile_key=profile,
                section_keys=(section,),
                as_ctx=stale,
            )
    with pytest.raises(StepUpRequired):
        EX.request_list(school, who, "exam_coordinator", section_keys=(section,), as_ctx=stale)


def test_ADR_0021_udise_category_masked_without_permission_even_if_asked(
    school: Any, section: str
) -> None:
    """Decision 2: opting in without student.read_sensitive is refused (403), never silently
    downgraded; a holder who does not opt in gets the masked sheet."""
    EX.student(
        school,
        section_key=section,
        extra=[ValueIn(attribute_key="category", source="parent_form", value="sc")],
    )
    coordinator = school.people["exam_coordinator"]
    with pytest.raises(Forbidden) as exc:
        EX.request_precheck(
            school,
            coordinator,
            "exam_coordinator",
            profile_key="udise-plus",
            section_keys=(section,),
            include_sensitive=True,
        )
    assert exc.value.code == "sensitive_not_allowed"
    principal = school.people["principal"]
    out = EX.request_precheck(
        school, principal, "principal", profile_key="udise-plus", section_keys=(section,)
    )
    EX.run(school, out.id)
    ready = _sheet(_xlsx(out.id), 2)
    assert ready[1][ready[0].index("Social category")] == "••••"


def test_precheck_permission_follows_profile_kind(school: Any, section: str) -> None:
    EX.student(school, section_key=section)
    board_only = dataclasses.replace(
        EX.ctx(school, school.people["exam_coordinator"], "exam_coordinator"),
        permissions=frozenset(
            {"export.board", "student.read_basic", "dq.findings.read", "session.authenticated"}
        ),
    )
    EX.request_precheck(
        school, school.people["exam_coordinator"], "", section_keys=(section,), as_ctx=board_only
    )
    with pytest.raises(Forbidden):
        EX.request_precheck(
            school,
            school.people["exam_coordinator"],
            "",
            profile_key="udise-plus",
            section_keys=(section,),
            as_ctx=board_only,
        )
    no_dq = dataclasses.replace(
        board_only, permissions=board_only.permissions - {"dq.findings.read"}
    )
    with pytest.raises(Forbidden):
        EX.request_precheck(
            school, school.people["exam_coordinator"], "", section_keys=(section,), as_ctx=no_dq
        )


def test_request_validation(school: Any, section: str, world: Any) -> None:
    principal = school.people["principal"]
    with pytest.raises(ValidationFailed) as exc:
        EX.request_precheck(school, principal, "principal", profile_key="no-such-profile")
    assert exc.value.errors[0]["code"] == "unknown_profile"
    with pytest.raises(ValidationFailed) as exc:
        EX.request_precheck(school, principal, "principal", section_keys=(section,))
    assert exc.value.errors[0]["code"] == "no_students"
    # Another school's section is an unknown reference (422), never a leak.
    school.ids["b_section"] = world.b.ids["section_9a"]
    with pytest.raises(ValidationFailed) as exc:
        EX.request_precheck(school, principal, "principal", section_keys=("b_section",))
    assert exc.value.errors[0]["code"] == "not_found"


def test_too_many_students(school: Any, section: str, monkeypatch: pytest.MonkeyPatch) -> None:
    from app.exports import config

    EX.student(school, section_key=section)
    EX.student(school, section_key=section)
    cfg = config.load_config()
    monkeypatch.setattr(exports, "load_config", lambda: cfg.model_copy(update={"max_students": 1}))
    with pytest.raises(ValidationFailed) as exc:
        EX.request_precheck(
            school, school.people["principal"], "principal", section_keys=(section,)
        )
    assert exc.value.errors[0]["code"] == "too_many_students"


# --- scope ---------------------------------------------------------------------------------------


def test_SEC_015_scoped_requester_gets_only_reachable_students(
    school: Any, section: str, admin_engine: Engine
) -> None:
    """A custom role with export.board limited to 9A: the whole-school request freezes only
    9A students."""
    inside = EX.student(school, section_key="section_9a")
    outside = EX.student(school, section_key=section)
    scoped = dataclasses.replace(
        EX.ctx(school, school.people["exam_coordinator"], "exam_coordinator"),
        scoped_permissions=frozenset({"student.read_basic", "dq.findings.read"}),
        scopes=Scopes(school=False, section_ids=frozenset({school.ids["section_9a"]})),
    )
    out = EX.request_precheck(
        school, school.people["exam_coordinator"], "", section_keys=(), as_ctx=scoped
    )
    ids = EX.export_row(admin_engine, out.id)["student_ids"]
    assert inside in ids
    assert outside not in ids


def test_permission_revoked_before_the_worker_runs_fails_the_export(
    school: Any, section: str, admin_engine: Engine
) -> None:
    EX.student(school, section_key=section)
    person = EX.W.add_member(admin_engine, school.tenant_id, ["exam_coordinator"])
    out = EX.request_precheck(school, person, "exam_coordinator", section_keys=(section,))
    with admin_engine.begin() as c:
        c.execute(
            text("DELETE FROM core.membership_roles WHERE membership_id = :m"),
            {"m": person.membership_id},
        )
    assert EX.run(school, out.id) == "failed"
    row = EX.export_row(admin_engine, out.id)
    assert (row["status"], row["error_code"]) == ("failed", "permission_revoked")
    assert EX.files(admin_engine, out.id) == []
    assert [r["action"] for r in EX.audit_rows(admin_engine, school.tenant_id, out.id)] == [
        "export.requested",
        "export.failed",
    ]
    assert EX.notifications(admin_engine, school.tenant_id, out.id) == [
        ("export.failed", person.membership_id)
    ]
    # Finished exports are left alone (idempotent worker).
    assert EX.run(school, out.id) == "failed"


# --- student list --------------------------------------------------------------------------------


def test_student_list_csv(school: Any, section: str, admin_engine: Engine) -> None:
    EX.student(school, section_key=section, roll_no="7", name='=HYPERLINK("x")')
    owner = school.people["owner"]
    out = EX.request_list(
        school,
        owner,
        "owner",
        columns=("admission_no", "full_name", "dob", "class", "section", "roll_no"),
        section_keys=(section,),
    )
    assert out.kind == "student_list"
    assert EX.run(school, out.id) == "ready"
    text_ = EX.stored(out.id, "csv").decode("utf-8")
    rows = list(csv.reader(io.StringIO(text_.lstrip("﻿"))))
    assert rows[0] == [
        "Generated by SchoolOS for internal checking · అంతర్గత తనిఖీ కోసం SchoolOS రూపొందించింది"
    ]
    assert rows[1] == [
        "Admission number",
        "Full name",
        "Date of birth",
        "Class",
        "Section",
        "Roll number",
    ]
    assert rows[2][1] == '\'=HYPERLINK("x")', "SEC-017"
    assert rows[2][2:] == ["14/03/2012", "IX", school_section_name(school, section), "7"]


def school_section_name(school: Any, key: str) -> str:
    from app.tenancy import service as tenancy

    with tenant_session(school.tenant_id) as db:
        return tenancy.get_section(db, school.ids[key]).name


def test_student_list_sensitive_columns(school: Any, section: str, admin_engine: Engine) -> None:
    EX.student(
        school,
        section_key=section,
        extra=[
            ValueIn(attribute_key="aadhaar_last4", source=AAD, value="4821"),
            ValueIn(attribute_key="health_notes", source="parent_form", value="Synthetic note"),
        ],
    )
    coordinator = school.people["exam_coordinator"]
    with pytest.raises(Forbidden) as exc:
        EX.request_list(
            school, coordinator, "exam_coordinator", columns=("full_name", "health_notes")
        )
    assert exc.value.code == "sensitive_not_allowed"
    with pytest.raises(ValidationFailed) as bad:
        EX.request_list(
            school,
            school.people["principal"],
            "principal",
            columns=("full_name", "aadhaar_name_as_printed", "no_such_column"),
        )
    assert [e["field"] for e in bad.value.errors] == ["columns.1", "columns.2"]
    assert {e["code"] for e in bad.value.errors} == {"column_not_exportable"}

    out = EX.request_list(
        school,
        school.people["principal"],
        "principal",
        columns=("full_name", "aadhaar_last4", "health_notes"),
        section_keys=(section,),
        fmt="xlsx",
    )
    assert out.include_sensitive is True
    EX.run(school, out.id)
    rows = _sheet(_xlsx(out.id), 0)
    assert rows[1][1] == "XXXX XXXX 4821", "PRV-014 display format"
    assert rows[1][2] == "Synthetic note"
    requested = EX.audit_rows(admin_engine, school.tenant_id, out.id)[0]["summary"]
    assert requested["sensitive_columns"] == ["aadhaar_last4", "health_notes"]


def test_invariant_4_no_full_aadhaar_in_any_export_cell(school: Any, section: str) -> None:
    from app.core.redaction import verhoeff_check_digit

    body = "45678901234"
    number = body + verhoeff_check_digit(body)
    # Values cannot hold an Aadhaar number (rejected on input), so plant one in the school
    # name (C0 text shown in every export) to prove the cell pipeline masks it.
    EX.student(school, section_key=section)
    out = EX.request_precheck(
        school, school.people["principal"], "principal", section_keys=(section,)
    )
    _plant_school_name(school, f"Synthetic School {number}")
    try:
        EX.run(school, out.id)
    finally:
        _plant_school_name(school, "Synthetic Model School")
    for ws in _xlsx(out.id).worksheets:
        for row in ws.iter_rows():
            for cell in row:
                assert not contains_full_aadhaar(str(cell.value or ""))
    assert number not in EX.FAKE.pages[-1]
    assert "XXXX XXXX " + number[-4:] in EX.FAKE.pages[-1]


_ADMIN: list[Engine] = []


def _plant_school_name(school: Any, name: str) -> None:
    engine = _ADMIN[0]
    with engine.begin() as c:
        c.execute(
            text("UPDATE core.tenants SET name = :n WHERE id = :t"),
            {"n": name, "t": school.tenant_id},
        )


@pytest.fixture(autouse=True)
def _admin(admin_engine: Engine) -> None:
    if not _ADMIN:
        _ADMIN.append(admin_engine)


# --- reads, downloads, retention ------------------------------------------------------------------


def test_read_and_download_only_own_exports(
    school: Any, section: str, admin_engine: Engine
) -> None:
    EX.student(school, section_key=section)
    mine = EX.ready_export(school, "exam_coordinator")
    me = school.people["exam_coordinator"]
    other = school.people["coordinator_2"]
    c_me = EX.ctx(school, me, "exam_coordinator")
    c_other = EX.ctx(school, other, "exam_coordinator")
    with tenant_session(school.tenant_id, me.user_id) as db:
        assert exports.get_export(db, c_me, mine).status == "ready"
        assert mine in {e.id for e in exports.list_exports(db, c_me).data}
        link = exports.download_url(db, c_me, mine, "xlsx")
    assert link.url.startswith("https://s3.synthetic.test/")
    assert f"/exports/{mine}/" in link.url
    assert link.filename.startswith("schoolos-precheck-cisce-registration-2026-")
    assert (link.expires_at - dt.datetime.now(dt.UTC)).total_seconds() <= 300
    gets = EX.D.memory_store().gets
    assert gets[-1]["disposition"].startswith("attachment;")
    with tenant_session(school.tenant_id, other.user_id) as db:
        with pytest.raises(NotFound):
            exports.get_export(db, c_other, mine)
        with pytest.raises(NotFound):
            exports.download_url(db, c_other, mine)
        assert mine not in {e.id for e in exports.list_exports(db, c_other).data}
    downloaded = [
        r
        for r in EX.audit_rows(admin_engine, school.tenant_id, mine)
        if r["action"] == "export.downloaded"
    ]
    assert len(downloaded) == 1
    assert downloaded[0]["summary"]["format"] == "xlsx"


def test_ADR_0021_read_all_and_download_any_rules(
    school: Any, section: str, admin_engine: Engine
) -> None:
    EX.student(school, section_key=section)
    theirs = EX.ready_export(school, "exam_coordinator")
    who = school.people["coordinator_2"]
    base = EX.ctx(school, who, "exam_coordinator")
    with tenant_session(school.tenant_id, who.user_id) as db:
        # Neither permission: someone else's export does not exist for you.
        with pytest.raises(NotFound):
            exports.get_export(db, base, theirs)
        with pytest.raises(NotFound):
            exports.download_url(db, base, theirs)
        with pytest.raises(Forbidden):
            exports.list_exports(db, base, requested_by="all")
        # export.read_all only: details yes, files no (403 not_own_export).
        reader = dataclasses.replace(base, permissions=base.permissions | {"export.read_all"})
        seen = exports.get_export(db, reader, theirs)
        assert (seen.own, seen.can_download) == (False, False)
        assert seen.requested_by.membership_id == school.people["exam_coordinator"].membership_id
        assert theirs in {e.id for e in exports.list_exports(db, reader, requested_by="all").data}
        with pytest.raises(Forbidden) as exc:
            exports.download_url(db, reader, theirs)
        assert exc.value.code == "not_own_export"
        # export.download_any (custom role): files with step-up, but never beyond your reach.
        anyone = dataclasses.replace(base, permissions=base.permissions | {"export.download_any"})
        with pytest.raises(NotFound):
            exports.get_export(db, anyone, theirs)  # details need export.read_all
        stale = dataclasses.replace(anyone, auth_time=None)
        with pytest.raises(StepUpRequired):
            exports.download_url(db, stale, theirs)
        scoped = dataclasses.replace(
            anyone,
            scoped_permissions=frozenset({"student.read_basic"}),
            scopes=Scopes(school=False, section_ids=frozenset({school.ids[section]})),
        )
        with pytest.raises(Forbidden):
            exports.download_url(db, scoped, theirs)
        link = exports.download_url(db, anyone, theirs)
    assert f"/exports/{theirs}/" in link.url
    downloaded = [
        r
        for r in EX.audit_rows(admin_engine, school.tenant_id, theirs)
        if r["action"] == "export.downloaded"
    ]
    assert len(downloaded) == 1
    assert downloaded[0]["actor_id"] == who.user_id
    assert downloaded[0]["summary"]["own_export"] is False


def test_ADR_0021_download_any_of_restricted_values_needs_school_wide_sensitive(
    school: Any, section: str
) -> None:
    EX.student(school, section_key=section)
    admin = school.people["office_admin"]
    out = EX.request_precheck(
        school,
        admin,
        "office_admin",
        profile_key="udise-plus",
        section_keys=(section,),
        formats=("xlsx",),
        include_sensitive=True,
    )
    assert EX.run(school, out.id) == "ready"
    owner = school.people["owner"]
    c_owner = EX.ctx(school, owner, "owner")
    no_sensitive = dataclasses.replace(
        c_owner, permissions=c_owner.permissions - {"student.read_sensitive"}
    )
    scoped_sensitive = dataclasses.replace(
        c_owner,
        scoped_permissions=frozenset({"student.read_sensitive"}),
        scopes=Scopes(school=False, section_ids=frozenset({school.ids[section]})),
    )
    with tenant_session(school.tenant_id, owner.user_id) as db:
        for ctx in (no_sensitive, scoped_sensitive):
            assert exports.get_export(db, ctx, out.id).can_download is False
            with pytest.raises(Forbidden) as exc:
                exports.download_url(db, ctx, out.id)
            assert exc.value.code == "sensitive_not_allowed"
        assert exports.download_url(db, c_owner, out.id).format == "xlsx"


def test_FR_EXP_004_student_list_download_needs_step_up(school: Any, section: str) -> None:
    EX.student(school, section_key=section)
    export_id = EX.ready_export(school, "owner")
    owner = school.people["owner"]
    stale = dataclasses.replace(
        EX.ctx(school, owner, "owner"), auth_time=dt.datetime.now(dt.UTC) - dt.timedelta(minutes=6)
    )
    with tenant_session(school.tenant_id, owner.user_id) as db:
        with pytest.raises(StepUpRequired):
            exports.download_url(db, stale, export_id)
        assert exports.download_url(db, EX.ctx(school, owner, "owner"), export_id).format == "csv"


def test_download_states(school: Any, section: str, admin_engine: Engine) -> None:
    EX.student(school, section_key=section)
    person = school.people["principal"]
    c = EX.ctx(school, person, "principal")
    queued = EX.queued_export(school, "principal")
    with tenant_session(school.tenant_id, person.user_id) as db, pytest.raises(Conflict) as exc:
        exports.download_url(db, c, queued)
    assert exc.value.code == "export_not_ready"
    ready = EX.ready_export(school, "principal")
    with tenant_session(school.tenant_id, person.user_id) as db, pytest.raises(NotFound):
        exports.download_url(db, c, ready, "csv")


def test_docs_05_13_files_purged_after_seven_days(
    school: Any, section: str, admin_engine: Engine
) -> None:
    EX.student(school, section_key=section)
    export_id = EX.ready_export(school, "principal")
    store = EX.D.memory_store()
    prefix = f"t/{school.tenant_id}/exports/{export_id}/"
    assert any(k.startswith(prefix) for k in store.objects)
    later = dt.datetime.now(dt.UTC) + dt.timedelta(days=7, minutes=1)
    assert exports.purge_expired(school.tenant_id, now=later) >= 1
    assert not any(k.startswith(prefix) for k in store.objects)
    row = EX.export_row(admin_engine, export_id)
    assert row["status"] == "expired"
    assert row["files_deleted_at"] is not None
    assert row["student_ids"], "the record of which students stays"
    actions = [r["action"] for r in EX.audit_rows(admin_engine, school.tenant_id, export_id)]
    assert actions[-1] == "export.expired"
    person = school.people["principal"]
    with tenant_session(school.tenant_id, person.user_id) as db, pytest.raises(Conflict) as exc:
        exports.download_url(db, EX.ctx(school, person, "principal"), export_id)
    assert exc.value.code == "export_expired"
    with tenant_session(school.tenant_id, person.user_id) as db:
        assert exports.get_export(db, EX.ctx(school, person, "principal"), export_id).files == []


def test_list_profiles(school: Any) -> None:
    profiles = exports.list_profiles(EX.ctx(school, school.people["principal"], "principal"))
    keys = {p.key: p for p in profiles}
    assert keys["cisce-registration-2026"].kind == "board"
    assert keys["cisce-registration-2026"].permission == "export.board"
    assert keys["udise-plus"].permission == "export.portal"
    assert all(p.allowed for p in profiles)
    assert keys["udise-plus"].fields[:2] == ["admission_no", "full_name"]
