"""Safe cells and writers: formula injection (SEC-017) and Aadhaar masking in every exported
cell (invariant 4, PRV-013, PRV-015); watermark (FR-EXP-003, US-901 AC2)."""

from __future__ import annotations

import csv
import io
import zipfile

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st
from openpyxl import load_workbook

from app.core.redaction import contains_full_aadhaar, verhoeff_check_digit
from app.exports.tables import (
    FORMULA_TRIGGERS,
    Table,
    clean_text,
    safe_cell,
    sheet_title,
    write_csv,
    write_xlsx,
)

WATERMARK = "Generated by SchoolOS for internal checking · అంతర్గత తనిఖీ కోసం SchoolOS రూపొందించింది"
INJECTIONS = [
    '=HYPERLINK("http://evil.test","click")',
    "=1+2",
    "+SUM(A1:A2)",
    "-2+3",
    "@SUM(A1)",
    "\t=1+1",
    "\r=1+1",
    "=cmd|' /C calc'!A0",
]


def _aadhaar() -> str:
    body = "23456789012"
    return body + verhoeff_check_digit(body)


def _csv_rows(data: bytes) -> list[list[str]]:
    text = data.decode("utf-8")
    assert text.startswith("﻿"), "BOM so Excel reads Telugu"
    return list(csv.reader(io.StringIO(text[1:])))


@pytest.mark.parametrize("value", INJECTIONS)
def test_SEC_017_formula_triggers_are_prefixed(value: str) -> None:
    out = safe_cell(value)
    assert out.startswith("'")
    assert out[1:] == value.replace("\x00", "")


@pytest.mark.parametrize("value", ["Venkata Sai", "K. Lakshmi", "9A", "", "2012-03-14"])
def test_SEC_017_ordinary_values_are_unchanged(value: str) -> None:
    assert safe_cell(value) == value


def test_SEC_017_none_is_an_empty_cell() -> None:
    assert safe_cell(None) == ""


def test_SEC_017_csv_cells_are_neutralised() -> None:
    table = Table(name="Students", header=("=H1", "Name"), rows=tuple((v, v) for v in INJECTIONS))
    rows = _csv_rows(write_csv(table, watermark=WATERMARK))
    assert rows[0] == [WATERMARK]
    assert rows[1][0] == "'=H1"
    for row in rows[2:]:
        for cell in row:
            assert cell.startswith("'"), cell
            assert not cell.startswith(FORMULA_TRIGGERS)


def test_SEC_017_xlsx_cells_are_text_never_formulas() -> None:
    table = Table(
        name="Findings", header=("Value", "@header"), rows=tuple((v, v) for v in INJECTIONS)
    )
    data = write_xlsx([table], watermark=WATERMARK, title="=title")
    wb = load_workbook(io.BytesIO(data))
    ws = wb["Findings"]
    assert ws["B1"].value == "'@header"
    for row in ws.iter_rows(min_row=2):
        for cell in row:
            assert cell.data_type == "s", (cell.coordinate, cell.data_type)
            assert isinstance(cell.value, str)
            assert cell.value.startswith("'")
    # The raw sheet XML holds no formula element at all.
    with zipfile.ZipFile(io.BytesIO(data)) as z:
        sheet_xml = z.read("xl/worksheets/sheet1.xml").decode()
    assert "<f>" not in sheet_xml
    assert "<f " not in sheet_xml
    assert wb.properties.title == "'=title"


def test_invariant_4_aadhaar_masked_in_every_cell_csv_and_xlsx() -> None:
    number = _aadhaar()
    spaced = f"{number[:4]} {number[4:8]} {number[8:]}"
    values = (number, f"ID {spaced} noted", f"={number}")
    table = Table(name="S", header=(f"Header {number}", "b", "c"), rows=(values,))
    csv_text = write_csv(table, watermark=f"{WATERMARK} {number}").decode()
    assert number not in csv_text
    assert not contains_full_aadhaar(csv_text)
    assert "XXXX XXXX " + number[-4:] in csv_text
    wb = load_workbook(io.BytesIO(write_xlsx([table], watermark=WATERMARK, title=number)))
    for ws in wb.worksheets:
        for row in ws.iter_rows():
            for cell in row:
                assert not contains_full_aadhaar(str(cell.value or "")), cell.coordinate
    assert not contains_full_aadhaar(wb.properties.title or "")


@settings(max_examples=300, deadline=None)
@given(st.text(max_size=80))
def test_SEC_017_property_no_cell_can_start_a_formula(text: str) -> None:
    out = safe_cell(text)
    assert not out.startswith(FORMULA_TRIGGERS)
    assert not contains_full_aadhaar(out)


@settings(max_examples=200, deadline=None)
@given(st.from_regex(r"[2-9][0-9]{10}", fullmatch=True), st.sampled_from(["", " ", "-", "=", "@"]))
def test_invariant_4_property_verhoeff_numbers_never_survive(body: str, prefix: str) -> None:
    number = body + verhoeff_check_digit(body)
    assert number not in safe_cell(prefix + number)
    assert number not in clean_text(number)


def test_control_characters_are_removed_but_line_breaks_kept() -> None:
    assert clean_text("A\x00B\x07C\nD") == "ABC\nD"


def test_xlsx_watermark_in_print_header_and_telugu_kept() -> None:
    table = Table(name="సారాంశం", header=("పూర్తి పేరు",), rows=(("వెంకట సాయి",),))
    wb = load_workbook(io.BytesIO(write_xlsx([table], watermark=WATERMARK, title="t")))
    ws = wb.worksheets[0]
    assert ws.title == "సారాంశం"
    assert ws["A2"].value == "వెంకట సాయి"
    header = ws.oddHeader
    assert header is not None
    assert "Generated by SchoolOS for internal checking" in (header.center.text or "")
    assert ws.freeze_panes == "A2"


def test_sheet_titles_are_valid_and_unique() -> None:
    used: set[str] = set()
    a = sheet_title("Ready to enter: 9A/9B [x]", used)
    b = sheet_title("Ready to enter: 9A/9B [x]", used)
    assert a != b
    for title in (a, b):
        assert len(title) <= 31
        assert not set(title) & set("[]:*?/\\")


@pytest.mark.parametrize(
    "value",
    [
        " =1+1",
        "\u00a0=1+1",
        "\u3000@SUM(A1)",
        "\n+1+1",
        "\uff1d1+1",
        "\uff0b1",
        "\uff0d1+1",
        "\uff20x",
    ],
)
def test_DL_hardening_4_hidden_and_full_width_formulas_are_prefixed(value: str) -> None:
    assert safe_cell(value).startswith("'")
    table = Table(name="Students", header=("h",), rows=((value,),))
    assert _csv_rows(write_csv(table, watermark=WATERMARK))[2][0].startswith("'")


def test_rows_must_match_header() -> None:
    with pytest.raises(ValueError, match="one value per header"):
        Table(name="x", header=("a", "b"), rows=(("only one",),))
