"""Export profiles are versioned configuration (FR-EXP-001, US-901 AC1, CLAUDE.md §6.13)."""

from __future__ import annotations

from typing import Any

import pytest
import yaml
from pydantic import ValidationError

from app.dq import service as dq
from app.exports.config import CONFIG_PATH, REQUIRED_LABELS, load_config, parse_config


def _raw() -> dict[str, Any]:
    data: dict[str, Any] = yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8"))
    return data


def test_FR_EXP_001_config_loads_with_versions() -> None:
    cfg = load_config()
    assert cfg.version >= 1
    assert cfg.retention_days == 7  # docs/05 §13
    assert cfg.download_url_ttl_s <= 300  # FR-DOC-004
    assert set(cfg.labels) >= REQUIRED_LABELS
    for layout in cfg.profiles.values():
        assert layout.layout_version >= 1


def test_FR_EXP_001_every_layout_matches_a_dq_profile_and_lists_its_required_fields() -> None:
    cfg = load_config()
    catalog = {p.key: p for p in dq.profiles_catalog()}
    assert set(cfg.profiles) == set(catalog), "one layout per DQ profile"
    for key, layout in cfg.profiles.items():
        missing = set(catalog[key].required_fields) - set(layout.fields)
        assert not missing, (key, missing)


@pytest.mark.usefixtures("telugu_on")  # Telugu output: switched on (ADR-0036)
def test_US_901_watermark_text_in_both_languages() -> None:
    cfg = load_config()
    assert cfg.watermark.en == "Generated by SchoolOS for internal checking"
    assert any("ఀ" <= ch <= "౿" for ch in cfg.watermark.te)
    assert cfg.watermark.en in cfg.watermark_text()
    assert cfg.watermark.te in cfg.watermark_text()


def test_ADR_0036_watermark_and_labels_are_english_while_telugu_is_hidden() -> None:
    cfg = load_config()
    assert cfg.watermark_text() == cfg.watermark.en
    for key in cfg.labels:
        assert cfg.label(key, "te") == cfg.label(key, "en")
        assert not any("ఀ" <= ch <= "౿" for ch in cfg.label(key, "te"))


def test_PRV_013_aadhaar_as_printed_fields_are_never_exported() -> None:
    cfg = load_config()
    assert cfg.never_exported >= {
        "aadhaar_name_as_printed",
        "aadhaar_dob_as_printed",
        "aadhaar_gender_as_printed",
    }
    assert cfg.aadhaar_last4_display.format(last4="1234") == "XXXX XXXX 1234"  # PRV-014


def test_FR_EXP_001_bad_configs_are_rejected() -> None:
    raw = _raw()
    raw["profiles"]["udise-plus"]["fields"].append("aadhaar_dob_as_printed")
    with pytest.raises(ValidationError, match="never exported"):
        parse_config(raw)
    raw = _raw()
    raw["aadhaar_last4_display"] = "1234 {last4}"
    with pytest.raises(ValidationError):
        parse_config(raw)
    raw = _raw()
    del raw["labels"]["col_route"]
    with pytest.raises(ValidationError, match="col_route"):
        parse_config(raw)
    raw = _raw()
    raw["profiles"]["udise-plus"]["date_format"] = "%d/%m/%Y %H"
    with pytest.raises(ValidationError):
        parse_config(raw)
    raw = _raw()
    raw["download_url_ttl_s"] = 3600
    with pytest.raises(ValidationError):
        parse_config(raw)
